<a href="https://colab.research.google.com/github/shubhamssingh8877-cmd/NumPy_Mastery/blob/main/Session_13_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #vector
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b=np.array([[1,2,3],[3,5,5]]) #matrix
print(b)

[[1 2 3]
 [3 5 5]]


In [ ]:
c=np.array([[[1,3,4],[4,5,4]],[[2,4,6],[3,6,8]]]) #tensor
print(c)

[[[1 3 4]
  [4 5 4]]

 [[2 4 6]
  [3 6 8]]]


In [ ]:
np.array([1,2,3],dtype=float) #complex,bool


array([1., 2., 3.])

In [ ]:
np.arange(1,11,3) #range between them

array([ 1,  4,  7, 10])

In [ ]:
np.arange(1,13).reshape(6,2) #reshape or making matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.ones((3,4)) #matrix where one no. is one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.linspace(-10,10,10,dtype=int) #gives the equal distace numbers{float by default}

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
np.random.random((2,5)) #gives random values

array([[0.76847051, 0.59590596, 0.67099704, 0.30080186, 0.17351826],
       [0.41918116, 0.60291382, 0.04352372, 0.53683187, 0.31513718]])

In [ ]:
np.identity(4) #digonal no. is one

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Attributes

In [ ]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2) # 2 arrays of dimention 2 row and 2 column(2,2,2)

a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3.ndim #no. of dimentions in an array

3

In [ ]:
a2.shape
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a2.size # no of items in array

12

In [ ]:
a2.itemsize #size means byte so default 8

In [ ]:
print(a1.dtype) #data type of items
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


**Changing** **DataTypes**

In [ ]:
a3.astype(np.int32) #manage the byte the data type by optimize memory

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**ARRAY OPERATIONS**

In [ ]:
a1=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a1*2 # all arithemetic operations can do.{SCALAR OPERATIONS} means for sigle array so scalar operations

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
a2!=2 #relational operator

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a1*a2 #{VECTOR OPERATIONS}

array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.]])

**ARRAY FUNCTIONS**

In [ ]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1


array([[64.,  4., 64.],
       [37., 52., 80.],
       [70., 61.,  9.]])

In [ ]:
np.min(a1) # we can any operation like mix,max,prod,sum so it will calculate by all items in that array.
np.sum(a1)
np. prod(a1)
# 0--> col,1-->row
np.max(a1,axis=0)
np.prod(a1,axis=1)


array([ 16384., 153920.,  38430.])

In [ ]:
np.mean(a1,axis=1) # we can also use row or column here
np.median(a1)
np.var(a1)
np.std(a1)

np.float64(25.32894698868383)

In [ ]:
np.sin(a1) #trigonometric functions

array([[ 0.92002604, -0.7568025 ,  0.92002604],
       [-0.64353813,  0.98662759, -0.99388865],
       [ 0.77389068, -0.96611777,  0.41211849]])

In [ ]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log & exponents
np.log(a1)
np.exp(a1)

array([[6.23514908e+27, 5.45981500e+01, 6.23514908e+27],
       [1.17191424e+16, 3.83100800e+22, 5.54062238e+34],
       [2.51543867e+30, 3.10429794e+26, 8.10308393e+03]])

In [ ]:
np.round(np.random.random((3,3))*100) #round of
np.floor(np.random.random((3,3))*100) # nearest lower value
np.ceil(np.random.random((3,3))*100)  #nearest higher value



array([[10., 61., 26.],
       [62., 86., 51.],
       [37., 76.,  3.]])

**INdex and SLice**

In [ ]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a1
a2
# a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1[-1]    #indexing
a2[1,1]
a3[0,1,0]

np.int64(2)

In [ ]:
a1[2:10:2] # slicing
a2[1,:]

array([4, 5, 6, 7])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]
a2[1,::3]
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3=np.arange(27).reshape (3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1,:,1]
a3[2,1:,1:]
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

**ITERATION**

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


RESHAPING

In [ ]:
#reshape

In [ ]:
np.transpose(a2)      #convert the array in r to c

a2.T    #easier form

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a3.ravel()    #change any dimention in 1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

STACKING

In [ ]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5,a4)) #adding horizontaly

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
np.vstack((a4,a5,a5)) #adding vertically

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

SPLITTING

In [ ]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2) #spliting horizontally or cutting the array

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.vsplit(a4,3) #vertically

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]