<a href="https://colab.research.google.com/github/shubhamssingh8877-cmd/NumPy_Mastery/blob/main/session_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NP SORT

In [2]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([52, 59,  7,  8, 41, 28, 39,  1, 64, 12, 45, 49, 33, 53, 44])

In [5]:
b=np.random.randint(1,100,25).reshape(5,5)
b

array([[ 5,  6, 20, 83,  1],
       [ 7, 55, 15, 89, 86],
       [ 9, 33, 44, 65, 66],
       [76, 83, 38,  9, 95],
       [48, 68, 15,  2, 15]])

In [10]:
np.sort(a)
np.sort(a)[::-1] #for descending order

array([97, 91, 61, 60, 57, 55, 44, 40, 37, 32, 31, 26,  6,  4,  3])

In [11]:
np.sort(b)
np.sort(b,axis=0)   #for column wise

array([[ 5,  6, 15,  2,  1],
       [ 7, 33, 15,  9, 15],
       [ 9, 55, 20, 65, 66],
       [48, 68, 38, 83, 86],
       [76, 83, 44, 89, 95]])

NP APPEND

In [12]:
np.append(a,200)

array([  3,  31,  26,  61,   4,  44,  40,  55,  32,  60,   6,  97,  37,
        91,  57, 200])

In [23]:
b
np.append(b,np.ones((b.shape[0],1)),axis=1)
np.append(b,np.random.random((b.shape[0],1)),axis=1)


array([[ 5.        ,  6.        , 20.        , 83.        ,  1.        ,
         0.95533579],
       [ 7.        , 55.        , 15.        , 89.        , 86.        ,
         0.18218924],
       [ 9.        , 33.        , 44.        , 65.        , 66.        ,
         0.39662168],
       [76.        , 83.        , 38.        ,  9.        , 95.        ,
         0.98743112],
       [48.        , 68.        , 15.        ,  2.        , 15.        ,
         0.77066811]])

NP.CONCatenate


In [9]:
c=np.arange(6).reshape(3,2)
d=np.arange(6,12).reshape(3,2)
print(c)
print(d)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [11]:
np.concatenate((c,d),axis=0)
#vstack

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [12]:
np.concatenate((c,d),axis=0) #hstack

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

NP.UNIQUE

In [14]:
e=np.array([1,2,2,3,4,2,4,3,6])
np.unique(e)

array([1, 2, 3, 4, 6])

np.expand_dims

In [19]:
a
a.shape #knowing the size or items in an array

(15,)

In [26]:
#expand the size of array like 1d to 2d or 2d to 3d
a
np.expand_dims(a,axis=0)
np.expand_dims(a,axis=0).shape

(1, 15)

In [23]:
np.expand_dims(a,axis=1)

array([[52],
       [59],
       [ 7],
       [ 8],
       [41],
       [28],
       [39],
       [ 1],
       [64],
       [12],
       [45],
       [49],
       [33],
       [53],
       [44]])

**np.where**

In [24]:
a

array([52, 59,  7,  8, 41, 28, 39,  1, 64, 12, 45, 49, 33, 53, 44])

In [25]:
#find where or which index is follows this condition
np.where(a>50)

(array([ 0,  1,  8, 13]),)

In [27]:
# changing the number where this condition follows
#np.where(condition,true,false)
np.where(a>50,0,a)

array([ 0,  0,  7,  8, 41, 28, 39,  1,  0, 12, 45, 49, 33,  0, 44])

In [28]:
np.where(a%2==0,0,a) #even numbers

array([ 0, 59,  7,  0, 41,  0, 39,  1,  0,  0, 45, 49, 33, 53,  0])

NP.argmax

In [29]:
a

array([52, 59,  7,  8, 41, 28, 39,  1, 64, 12, 45, 49, 33, 53, 44])

In [50]:
# to find the lowest or largest index in one line
np.argmax(a) #np.argmin(a)

np.int64(8)

In [45]:
b=np.arange(24).reshape(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
np.argmax(b,axis=0)

array([3, 3, 3, 3, 3, 3])

np.cumsum()

In [52]:
a

array([52, 59,  7,  8, 41, 28, 39,  1, 64, 12, 45, 49, 33, 53, 44])

In [53]:
np.cumsum(a)

array([ 52, 111, 118, 126, 167, 195, 234, 235, 299, 311, 356, 405, 438,
       491, 535])

In [54]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [58]:
np.cumsum(b,axis=0) #comulative sum where 0-> column and 1->row

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14, 16],
       [18, 21, 24, 27, 30, 33],
       [36, 40, 44, 48, 52, 56]])

In [59]:
np.cumprod(a)

array([                 52,                3068,               21476,
                    171808,             7044128,           197235584,
                7692187776,          7692187776,        492300017664,
             5907600211968,     265842009538560,   13026258467389440,
        429866529423851520, 4336181985754578944, 6324566636105957376])

PERCENTILE

In [60]:
a

array([52, 59,  7,  8, 41, 28, 39,  1, 64, 12, 45, 49, 33, 53, 44])

In [61]:
np.percentile(a,100) #percentile means how many no. or of people ahead or back
# formula(n/N x100)
# we can use any number percentile

np.float64(64.0)

NP.HISTOGRAM

In [62]:
a

array([52, 59,  7,  8, 41, 28, 39,  1, 64, 12, 45, 49, 33, 53, 44])

In [63]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80]) #how many number between the bins or range of bar graph

(array([3, 1, 1, 2, 4, 3, 1, 0]), array([ 0, 10, 20, 30, 40, 50, 60, 70, 80]))

np.**corrcoef**

In [65]:
salary=np.array([20000,40000,50000,60000]) #tell that the relation that if 0 then no change,1 then increase and -1 then decrease in the two relation
experience=np.array([1,3,2,5])
np.corrcoef(salary,experience)

array([[1.        , 0.82857143],
       [0.82857143, 1.        ]])

np.**isin**

In [66]:
a

array([52, 59,  7,  8, 41, 28, 39,  1, 64, 12, 45, 49, 33, 53, 44])

In [68]:
items=[10,20,30,40,50,60,59,64]
a[np.isin(a,items)]

array([59, 64])

np.**flip**

In [69]:
a

array([52, 59,  7,  8, 41, 28, 39,  1, 64, 12, 45, 49, 33, 53, 44])

In [70]:
np.flip(a)

array([44, 53, 33, 49, 45, 12, 64,  1, 39, 28, 41,  8,  7, 59, 52])

In [71]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [73]:
np.flip(b)
np.flip(b,axis=0)

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

np.**put**

In [76]:
a

array([110, 530,   7,   8,  41,  28,  39,   1,  64,  12,  45,  49,  33,
        53,  44])

In [79]:
np.put(a,[0,1],[110,530]) # change multiple items in an array
a

array([110, 530,   7,   8,  41,  28,  39,   1,  64,  12,  45,  49,  33,
        53,  44])

np.**delete**

In [80]:
a

array([110, 530,   7,   8,  41,  28,  39,   1,  64,  12,  45,  49,  33,
        53,  44])

In [82]:
np.delete(a,[0,2,4]) # deleting any items or multiple

array([530,   8,  28,  39,   1,  64,  12,  45,  49,  33,  53,  44])

SET **FUNCTION**

In [83]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [87]:
np.intersect1d(m,n)

array([3, 4, 5])

In [86]:
np.setdiff1d(n,m)

array([6, 7])

In [88]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [92]:
m[np.in1d(m,1)]

/tmp/ipykernel_2381/524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

np.**clip**

In [93]:
a

array([110, 530,   7,   8,  41,  28,  39,   1,  64,  12,  45,  49,  33,
        53,  44])

In [95]:
np.clip(a,a_min=25,a_max=36)

array([36, 36, 25, 25, 36, 28, 36, 25, 36, 25, 36, 36, 33, 36, 36])